# Generated by Django 4.2.2 on 2023-06-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slugs',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
